module.exports = {
  products: [
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 67,
      brand: "Giordano",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Nike Full-Zip Hoodie Men Workout  Sweatshirt",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.3,
      numReviews: 23,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 40,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 30,
      countInStock: 3,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sportstyle Tricot Joggers",
      category: "Pants",
      image: "/images/product-4.jpg",
      price: 90,
      brand: "Under Armour",
      rating: 4.7,
      numReviews: 40,
      countInStock: 9,
    },
    {
      _id: "5",
      name: "Champion Mens Graphic Powerblend Fleece Jogger",
      category: "Shirts",
      image: "/images/product-5.jpg",
      price: 112,
      brand: "Champion",
      rating: 4.1,
      numReviews: 120,
      countInStock: 3,
    },
    {
      _id: "6",
      name: "Royal Mens Joggers Pants Long Multi-Pockets",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 54,
      brand: "Royal",
      rating: 4.5,
      numReviews: 34,
      countInStock: 6,
    },
  ],
};
